services:
  backend:
    image: idinsight/experiment_engine_backend:latest
    build:
      context: ../../backend
      dockerfile: Dockerfile
    command: >
      /bin/sh startup.sh
    restart: always
    volumes:
      - temp:/usr/src/experiment_engine_backend/temp
    env_file:
      - .base.env
      - .backend.env
    depends_on:
      - relational_db
      - redis
    environment:
      - POSTGRES_HOST=relational_db
      - REDIS_HOST=redis://redis:6379

  frontend:
    image: idinsight/experiment_engine_frontend:latest
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    command: >
      node server.js
    depends_on:
      - backend
    restart: always
    env_file:
      - .base.env

  relational_db:
    image: postgres:16.4
    restart: always
    env_file:
      - .backend.env
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports: # Expose the port to port 5434 on the host machine for debugging
      - 5434:5432

  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .base.env

  redis:
    image: "redis:6.0-alpine"
    ports: # Expose the port to port 6380 on the host machine for debugging
      - "6380:6379"
    restart: always

volumes:
  db_volume:
  caddy_data:
  caddy_config:
  temp:
